/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  rules: {
    "selector-class-pattern": null,
    "custom-property-pattern": null,
    "keyframes-name-pattern": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-block-single-line-max-declarations": null,
    "shorthand-property-no-redundant-values": null,
    "color-function-notation": "legacy",
    "alpha-value-notation": null,
    "font-family-name-quotes": null,
    "rule-empty-line-before": null,
    "comment-empty-line-before": null,
    "declaration-empty-line-before": null,
    "at-rule-empty-line-before": null,
    "selector-attribute-quotes": null,
    "media-feature-range-notation": null,
    "property-no-vendor-prefix": null,
    "length-zero-no-unit": null,
    "custom-property-empty-line-before": null,
    "color-hex-length": null,
    "selector-pseudo-element-colon-notation": null,
    "selector-not-notation": null,
    "value-keyword-case": null,
    "scss/operator-no-newline-after": null,
    "lightness-notation": null,
    "hue-degree-notation": null,
  },
};
