#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { fileURLToPath } from "url";
import * as esbuild from "esbuild";
import { minify } from "terser";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, "..");
const distDir = path.join(rootDir, "dist");
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

function generateUserReleaseNotes() {
  const src = path.join(rootDir, "user-release-notes.json");
  const out = path.join(rootDir, "modules", "user-release-notes.generated.js");
  let data = { releases: [] };
  if (fs.existsSync(src)) {
    try {
      data = JSON.parse(fs.readFileSync(src, "utf8"));
    } catch (err) {
      console.warn(`⚠ Could not parse user-release-notes.json: ${err.message}`);
    }
  } else {
    console.warn("⚠ user-release-notes.json missing; using empty releases");
  }
  const body = `/* Generated by scripts/build.js — do not edit */\nconst BTFW_USER_RELEASE_NOTES = ${JSON.stringify(data)};\n`;
  const existing = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : null;
  if (existing === body) {
    return;
  }
  fs.writeFileSync(out, body, "utf8");
  console.log("✓ Generated modules/user-release-notes.generated.js");
}

// Bundle configurations - logically grouped modules
const bundles = [
  {
    name: 'core',
    modules: [
      'modules/util-motion.js',
      'modules/util-tmdb-proxy.js',
      'modules/feature-style-core.js',
      'modules/feature-bulma-layer.js',
      'modules/feature-layout.js'
    ]
  },
  {
    name: 'chat',
    modules: [
      'modules/feature-chat.js',
      'modules/feature-chat-tools.js',
      'modules/feature-chat-filters.js',
      'modules/feature-chat-username-colors.js',
      'modules/feature-chat-media.js',
      'modules/feature-chat-avatars.js',
      'modules/feature-chat-timestamps.js',
      'modules/feature-chat-ignore.js',
      'modules/feature-chat-commands.js',
      'modules/feature-drink-counter.js'
    ]
  },
  {
    name: 'player',
    modules: [
      'modules/feature-player.js',
      'modules/feature-stack.js',
      'modules/feature-video-overlay.js',
      'modules/feature-video-enhancements.js',
      'modules/feature-ambient.js',
      'modules/feature-pip.js',
      'modules/feature-resize.js',
      'modules/feature-audio-boost.js',
      'modules/feature-audio-enhancer.js',
      'modules/feature-auto-subs.js',
      'modules/feature-movie-info.js',
      'modules/feature-movie-suggestions.js'
    ]
  },
  {
    name: 'playlist',
    modules: [
      'modules/feature-nowplaying.js',
      'modules/feature-playlist-performance.js',
      'modules/feature-playlist-tools.js',
      'modules/feature-playlist-search.js'
    ]
  },
  {
    name: 'admin',
    modules: [
      'modules/user-release-notes.generated.js',
      'modules/util-theme-runtime.js',
      'modules/util-theme-presets.js',
      'modules/feature-channel-theme-admin.js',
      'modules/feature-theme-settings.js',
      'modules/feature-motd-editor.js'
    ]
  },
  {
    name: 'features',
    modules: [
      'modules/feature-footer.js',
      'modules/feature-navbar.js',
      'modules/feature-modal-skin.js',
      'modules/feature-emotes.js',
      'modules/feature-emoji-compat.js',
      'modules/feature-emoji-loader.js',
      'modules/util-giphy-proxy.js',
      'modules/util-klipy-proxy.js',
      'modules/feature-gifs.js',
      'modules/feature-poll-overlay.js',
      'modules/feature-notify.js',
      'modules/feature-notification-sounds.js',
      'modules/feature-sync-guard.js',
      'modules/feature-local-subs.js',
      'modules/feature-billcast.js',
      'modules/feature-billcaster.js',
      'modules/feature-overlays.js',
      'modules/feature-userlist-overlay.js',
      'modules/feature-ratings.js'
    ]
  }
];

async function buildBundle(bundle) {
  let code = `/*! Quiglytube ${bundle.name} bundle */\n`;

  for (const modulePath of bundle.modules) {
    const fullPath = path.join(rootDir, modulePath);
    if (!fs.existsSync(fullPath)) {
      console.warn(`⚠ Skipping missing module: ${modulePath}`);
      continue;
    }
    code += `\n/* ${modulePath} */\n` + fs.readFileSync(fullPath, "utf8");
  }

  // Pass combined code to Terser for minification
  const result = await minify(code, {
    compress: true,
    mangle: true,
    format: {
      comments: false
    }
  });

  const outPath = path.join(distDir, `${bundle.name}.bundle.js`);
  fs.writeFileSync(outPath, result.code, "utf-8");
  console.log(`✓ Built ${bundle.name}.bundle.js (${(result.code.length / 1024).toFixed(1)}KB)`);
}

async function buildFrameworkLoader() {
  const rootDir = path.join(__dirname, "..");
  const entry = path.join(rootDir, "src", "billtube-fw.js");
  const outfile = path.join(rootDir, "billtube-fw.js");
  await esbuild.build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: "iife",
    target: ["es2018"],
    logLevel: "silent"
  });
  console.log("✓ Built billtube-fw.js");
}

(async function build() {
  console.log("🔨 Building Quiglytube bundles with Terser...\n");
  generateUserReleaseNotes();
  await buildFrameworkLoader();
  for (const bundle of bundles) {
    await buildBundle(bundle);
  }
  console.log("\n✨ Build complete!");
  const verify = spawnSync(process.execPath, ["scripts/verify-dist.js"], {
    cwd: path.join(__dirname, ".."),
    stdio: "inherit"
  });
  if (verify.status !== 0) process.exit(verify.status || 1);
})();